title: Personal Page of Inhoe KOO
author: Inhoe KOO
email: ihkoo711@snu.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  I'm a Self-motivated sophomore student majoring in SNU Electrical & Computer engineering
  with experience in projects on various Neural Networks, Quantum computing, image
  processing by Computer vision.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Inhoe KOO
  tagline: Developer. Entreprenuer. Co-founder of ROUND
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    github:  InaeKOO
    twitter: 9inae
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
remote_theme: samarsault/texture
theme: texture
